# Generated by Django 5.2.6 on 2025-10-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analytics',
        ),
    ]
