# Generated by Django 5.2.6 on 2025-10-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_analytics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='UserActivity',
        ),
        migrations.AlterField(
            model_name='kolampattern',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='kolam_patterns/'),
        ),
    ]
