# Generated by Django 5.2.6 on 2025-10-27 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_feedback_delete_useractivity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KolamPattern',
        ),
    ]
