# Generated by Django 5.2.6 on 2025-10-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_delete_kolampattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='KolamDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='kolams/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
