# Generated by Django 5.2.15 on 2026-07-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_activitylog_design_folder_delete_kolamdesign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='user',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Design',
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
